
name: Deploying

on:
  push:
    branches:
      - master
      - feature/tests
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # or any version you are using

      - name: Install dependencies using lock file
        run: npm ci  # For npm, it installs dependencies using package-lock.json

      - name: Run tests
        run: npm test
deploy:
 Check failure on line 29 in .github/workflows/main2.yml


GitHub Actions
/ Deploying
Invalid workflow file
The workflow is not valid. .github/workflows/main2.yml (Line: 29, Col: 1): Unexpected value 'deploy'
  needs: test
  runs-on: ubuntu-latest
  steps:

      - name: Checkout code
        uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: nom install

  deploy:
    needs: build  # Ensure deploy job runs after build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
